# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, vNext ]
  pull_request:
    branches: [ master, vNext ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: wget http://download.mono-project.com/repo/xamarin.gpg
    - run: sudo apt-key add xamarin.gpg
    - run: echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee --append /etc/apt/sources.list.d/mono-xamarin.list
    - run: sudo apt-get update
    - run: sudo apt-get install mono-complete
    - run: mozroots --import --sync
    - run: brew install gdbm
    - run: brew install mpdecimal
    - run: brew install openssl
    - run: brew install ncurses
    - run: brew install docfx --ignore-dependencies
    - run: npm install
    - run: npm run build
